"""Add structured code symbols

Revision ID: a35f777f93f0
Revises: 541213361875
Create Date: 2026-08-24 17:11:50.223613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35f777f93f0'
down_revision: Union[str, Sequence[str], None] = '541213361875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_file_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('symbol_type', sa.String(length=100), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['code_file_id'], ['code_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_symbols_code_file_id'), 'code_symbols', ['code_file_id'], unique=False)
    op.create_index(op.f('ix_code_symbols_symbol_type'), 'code_symbols', ['symbol_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_symbols_symbol_type'), table_name='code_symbols')
    op.drop_index(op.f('ix_code_symbols_code_file_id'), table_name='code_symbols')
    op.drop_table('code_symbols')
    # ### end Alembic commands ###
